services:
  ai-api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.ai_api
    ports:
      - "8001:8001"
    command: uvicorn sd.ai_api:app --host 0.0.0.0 --port 8001 --reload
    restart: unless-stopped

  api:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.api
    ports:
      - "8000:8000"
    command: uvicorn sd.application:app --host 0.0.0.0 --port 8000 --reload
    environment:
      # Dependency instalation environments
      - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
      - PIP_TRUSTED_HOST=pypi.tuna.tsinghua.edu.cn
      # Entrypont
      - ENV=developments
      # Database
      - DATABASE_URL=postgresql://user:password@db:5432/demo
      - REDIS_URL=redis://redis:6379/0
      - AI_API_URL=http://ai-api:8001/predict
    depends_on:
      - db
      - redis
      - ai-api

  db:
    image: postgres:15-alpine
    environment:
      # Dependenci instalation environments
      - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
      - PIP_TRUSTED_HOST=pypi.tuna.tsinghua.edu.cn
      # Database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demo
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.worker
    command: celery -A sd.tasks worker --loglevel=info
    environment:
      - REDIS_URL=redis://redis:6379/0
      - AI_API_URL=http://ai-api:8001/predict
    depends_on:
      - redis
      - ai-api

volumes:
  postgres_data:
  redis_data: