services:
  api:
    build:
      context: .
      dockerfile: ./docker/entrypoint/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    environment:
      # Dependency instalation environments
      - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
      - PIP_TRUSTED_HOST=pypi.tuna.tsinghua.edu.cn
      # Entrypont
      - ENV=developments
      # Database
      - DATABASE_URL=postgresql://user:password@db:5432/demo

  db:
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      # Dependenci instalation environments
      - PIP_INDEX_URL=https://pypi.tuna.tsinghua.edu.cn/simple
      - PIP_TRUSTED_HOST=pypi.tuna.tsinghua.edu.cn
      # Database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=demo

volumes:
  postgres_data: